'use strict';
const $=id=>document.getElementById(id),sources=['Human','ScanDL 2.0','FinGaze'];
let example=0,chosen=[0,0,0],time=Infinity,playing=false,last=0,selectedWord=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const data=()=>window.EXAMPLES[example], events=i=>data().paths[sources[i]][chosen[i]];
const total=ev=>ev.reduce((s,e)=>s+e[1],0),maximum=()=>Math.max(1,...sources.map((_,i)=>total(events(i))));
function metrics(ev){if(!ev.length)return ['—','—','—'];const n=new Set(ev.map(e=>e[0])).size;return [(total(ev)/n).toFixed(1),(1-n/data().words.length).toFixed(3),(ev.filter((e,j)=>j&&e[0]<ev[j-1][0]).length/data().words.length).toFixed(3)];}
function stop(){playing=false;$('play').textContent='Play';}
function initialize(){stop();selectedWord=null;time=maximum();$('time').max=time;$('sentence').textContent=data().words.join(' ');$('cards').innerHTML=sources.map((s,i)=>`<section class="card"><h2>${s}</h2><p class="sub">${i?'PhraseBank pre-training · No fine-tuning':'Observed natural reading'}</p><label>Sample <select data-source="${i}"><option value="0">${i?'Generated path':'Reader'} 01</option><option value="1" ${chosen[i]===1?'selected':''}>${i?'Generated path':'Reader'} 02</option></select></label><div id="plot-${i}"></div><div class="metrics" id="metric-${i}"></div></section>`).join('');document.querySelectorAll('[data-source]').forEach(s=>s.onchange=()=>{chosen[+s.dataset.source]=+s.value;initialize();});draw();}
function draw(){const words=data().words;let x=14,y=60;const pos=words.map(w=>{const width=Math.min(310,w.length*8.5+8);if(x+width>335){x=14;y+=78;}const p={x,y,width};x+=width+8;return p;});const heat=sources.map((_,i)=>{const a=words.map(()=>0);events(i).forEach(([w,d])=>a[w]+=d);return a;});const high=Math.max(1,...heat.flat());
sources.forEach((s,i)=>{let content='',elapsed=0,previous=null,visits={};if($('mode').value==='path')events(i).forEach(([w,d],j)=>{const start=elapsed;elapsed+=d;if(start>=time)return;const p=pos[w],v=visits[w]||0;visits[w]=v+1;const cx=p.x+p.width/2+(v%3-1)*4,cy=p.y-23-Math.floor(v/3)*4;if(previous)content+=`<path d="M${previous.x},${previous.y} Q${(previous.x+cx)/2},${Math.min(previous.y,cy)-22} ${cx},${cy}" fill="none" stroke="${w<previous.w?'#c56a39':'#387da5'}" opacity=".6"/>`;content+=`<circle cx="${cx}" cy="${cy}" r="${Math.sqrt(d)*.48}" fill="#83b7cd" fill-opacity=".65" stroke="${elapsed>time?'#153c30':'white'}"/><text x="${cx}" y="${cy+3}" text-anchor="middle" font-size="9">${j+1}</text>`;previous={x:cx,y:cy,w};});
pos.forEach((p,w)=>{const ratio=heat[i][w]/high;const color=$('mode').value==='heat'?`hsl(145 30% ${96-ratio*54}%)`:'#f0f4ee';content+=`<g role="button" tabindex="0" data-word="${w}" aria-label="Word ${w+1}: ${esc(words[w])}"><rect x="${p.x}" y="${p.y-15}" width="${p.width}" height="24" rx="3" fill="${color}" stroke="${selectedWord===w?'#153c30':'none'}"/><text x="${p.x+3}" y="${p.y+2}" font-size="15" font-family="Georgia">${esc(words[w])}</text></g>`;});$('plot-'+i).innerHTML=`<svg viewBox="0 0 350 ${y+25}" role="img" aria-label="${s} trajectory">${content}</svg>`;$('metric-'+i).innerHTML=metrics(events(i)).map((v,j)=>`<span>${['TF (ms)','SR','RR'][j]}<br><strong>${v}</strong></span>`).join('');});
document.querySelectorAll('[data-word]').forEach(g=>{const select=()=>{selectedWord=+g.dataset.word;draw();};g.onclick=select;g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select();}};});$('time').value=Math.min(time,maximum());$('clock').textContent=`${Math.round(Math.min(time,maximum()))} / ${Math.round(maximum())} ms`;
$('inspector').innerHTML=selectedWord===null?'Select a word in any panel to inspect it.':`<strong>Word ${selectedWord+1}: ${esc(words[selectedWord])}</strong><table><tr><th>Source</th><th>Fixations</th><th>Total duration (ms)</th></tr>${sources.map((s,i)=>{const ev=events(i).filter(e=>e[0]===selectedWord);return `<tr><td>${s}</td><td>${ev.length}</td><td>${total(ev).toFixed(1)}</td></tr>`;}).join('')}</table>`;}
$('text').innerHTML=window.EXAMPLES.map((e,i)=>`<option value="${i}">${e.id} · ${e.words.length} words</option>`).join('');$('text').onchange=()=>{example=+$('text').value;chosen=[0,0,0];initialize();};$('mode').onchange=()=>{stop();$('play').disabled=$('mode').value==='heat';draw();};$('play').onclick=()=>{if(playing)stop();else{if(time>=maximum())time=0;playing=true;$('play').textContent='Pause';}};$('reset').onclick=()=>{stop();time=0;draw();};$('time').oninput=()=>{stop();time=+$('time').value;draw();};function tick(t){if(playing){time=Math.min(maximum(),time+t-last);draw();if(time>=maximum())stop();}last=t;requestAnimationFrame(tick);}initialize();requestAnimationFrame(tick);
